type Report = {
  _id: string;
  id: string;
  title: string;
  employmentRateGeneralOrder: string;
  employmentRateGeneralValue: string;
  employmentTimeGeneralOrder: string;
  employmentTimeGeneralValue: string;
  priceGeneralOrder: string;
  priceGeneralValue: string;
  qualityGeneralOrder: string[];
  qualityGeneralValue: string[];
  companyGeneralOrder: string;
  companyGeneralValue: string;
  publicGeneralOrder: string;
  publicGeneralValue: string;
  sectorDistributionTitle: string[];
  sectorDistributionContent: string[];
  sectorDistributionRate: string[];
  publicDistributionTitle: [];
  publicDistributionContent: [];
  publicDistributionRate: [];
  companyDistributionTitle: string[];
  companyDistributionContent: string[];
  companyDistributionRate: string[];
  priceDistributionTitle: string[];
  priceDistributionContent: string[];
  priceDistributionRate: string[];
  EmploymentTimeDistributionTitle: string[];
  EmploymentTimeDistributionContent: string[];
  EmploymentTimeDistributionRate: string[];
  year: string;
  sequence: string;
  created: string;
  updated: string;
  priceDistributionArray: { title: string; rate: string }[];
  companyDistributionArray: { title: string; rate: string }[];
  sectorDistributionArray: { title: string; rate: string }[];
};
