type Report = {
  _id: string;
  id: number;
  sequence: number;
  rec_status: number;
  updated: string;
  year: string;
  title: string;
  lQualityGeneralTitle: string[];
  lQualityGeneralRate: string[];
  publicGeneralOrder: string;
  publicGeneralValue: string;
  lSectorDistributionTitle: string[];
  lSectorDistributionRate: string[];
  lCompanyDistributionTitle: string[];
  lCompanyDistributionRate: string[];
  lPriceDistributionTitle: string[];
  lPriceDistributionRate: string[];
  lEmploymentTimeDistributionTitle: string[];
  lEmploymentTimeDistributionRate: string[];
  created: string;
};
